certbot_cloudflare_api_key: ENC[AES256_GCM,data:QeOqP0s1pPzJvcYloQ69DvV+oLrh9L7ZEAYvW11pATSbC4E+Dw==,iv:y7d1llKBMNAg24UC/F2HPeiXG0XwD4YIQJXH8wukCDU=,tag:P9XBJq2rkEzmYh+nooeUhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-23T19:07:04Z"
    mac: ENC[AES256_GCM,data:nWyeAe/tzZsQ5htNk9NZ5yJiwi9OClgjVYh5GFmMH4QuJXkxk9HqpO/WOcgJo4aqWUhdyOt+iT9D+BXc19MfKll7PPB1NAA5JaGpzft6JrudE2Kg0lx+FpwI8gJaH768Wu1A076ntuohcl8vBqbTeXCV8jKucxTMU2JasxV9xqc=,iv:5WivgY93LfmpyVvdCQR8Uwr44nrk7rPKpEPPhjndyA4=,tag:1mnsACaTBj1NONuo+OqGzg==,type:str]
    pgp:
        - created_at: "2023-08-23T19:07:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9GuoIL0zueSAQ/+JIuoNXFCytaMh9Umkky9MSfAsMsuK6w8fzfZp0K4T7+a
            WWJfXqWmOLXeXwahCETYC1PeCFAUd9+/YseUh404tVZlv7CUFUNCF3MnO9ltCs9C
            PdQbrs/XqAZMUEEX8pJ8LdaE74fiTS5CjbwcJw9dyQHrPK43ByQ9EuHQmCLNLkkM
            yIwCC2ta7i0maAg/VUBhtvXDSwAOpwWpcf4Khs+w/nosDPRiADPQhaYes6Rcv3ci
            ztoyZQngTVMzYf5MWUVIhCD7UtY3snLOQuCKnt2oL3YQmSNk+kT7PSGJqDY6ISNz
            XezLI/2EnWdx8oiX5Vuj0Q7FJw9mC2jC2ozQyv8MKNIXe87zhQkzd2XrODv4iani
            sAD+PSkatxeOgGki1lVjNLU7YVjgz4/MNwh2eY2f7SQl4ctjZJ15WL2kF8IqzzZe
            vUeJ2r+NVWryHKfWF1V2esMBLFRRIjKsflscIqyj9aCwUYJr886aoDRVwwt17K/j
            Ik34AMjKfqzCFELgJPsKpXq8PYpnfCIGg5EBJk1E7bHi6L8axk0dMCxZVrXM7vB+
            hcsFV+OohaBhnwKjC8mt3qle90z1yIUqULgTTNmecg+ZZ10oXBx2VBDMykV5MaCd
            ZxyENOzw94fZMfQnjNFewu4w/tbh/0rlOEkSSrMTZWXypAwtlVx9XnYsIKPdEbfS
            XgG2kDAlkV0omTIwEJg3RcBCk1IEGwRuA1Zwq0mCTAX8CItevRebZgc4pJ9qiwb1
            76MyJW8vJoLY6XPI96hoJBDozx2keDpLNybLlcfIls6WV+x95+WJtE8MOGkVKMs=
            =ZJZM
            -----END PGP MESSAGE-----
          fp: 8C37E68F808A5E8E14E547B41A69A2ACA7C505F7
    unencrypted_suffix: _unencrypted
    version: 3.7.3
