sudo: required

language: node_js

node_js:
  - '11'

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/showcasenodejs .

script:
  - npm run pre-commit

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/showcasenodejs;
    fi
