name: Node CI

on:
  push:
    branches: [ master ]

jobs:
  check:
    name: Run linter, tests and other stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.0
          cache: 'npm'
      - run: npm ci
      - run: npm run check-exact
      - run: npm run lint

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            risedphantom/showcasenodejs:latest
            risedphantom/showcasenodejs:${{ GITHUB_SHA }}
